platform :ios, '8.0'
target 'ZNDocument' do
pod 'AFNetworking'
pod 'UIView+AutoLayout'
pod 'SDWebImage'
pod 'FMDB'
pod 'MJExtension'
pod 'TYAttributedLabel'
pod 'MJRefresh'
pod 'PPSSignatureView'
pod 'pop'
pod 'Bugly'
pod 'LCActionSheet'
pod 'SAMKeychain'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'Pingpp'
pod 'FDFullscreenPopGesture'
pod 'ASIHTTPRequest'
pod 'ZFDownload'
end
